name: "zip"
description: "This GitHub action exposes the zip command for use in building/archiving"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  args:
    description: "CMD to run"
    required: false