name: "zip"
description: "Action that exposes the zip command for use in building/archiving. Same as montudor/action-zip but using non-root user"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  args:
    description: "CMD to run"
    required: false