name: GCP Sync
description: "Calls rsync on Google Cloud Storage"

inputs:
  to:  
    description: 'Directory where the project must be deployed to'
    required: true
  cloud_credentials:
    description: 'Credentials of the cloud service where the project will be deployed to'
    required: false
  cloud_bucket:
    description: 'Name of the Cloud service (eg. GCS) bucket'
    required: false
  cache:
    description: 'Enable or disable cache'
    required: true
  allowed_destination:
    description: 'Check the destination'
    required: true
    default: ''
  exclude:
    description: 'Regrex expression to exclude files'
    required: true
  path:
    description: 'PATH where the static files are located'
    required: true
  delete:
    description: 'Delete extra files in the destination not found in the source'
    required: true

runs:
  using: docker
  image: Dockerfile
