name: Prune
description: 'Removes the deployment from GCS or Github Pages and disbles the environment'

# Action to prune an environment and remove the associated files deployed in Github Pages or GCS
# Useful for example when a PR is closed and the associated deployment is not required anymore.
# Steps:
# - Disables the Github Environment object
# - Removes the directory in Github Pages
inputs:
  to:  
    description: 'Directory where the files are deployed'
    required: true
    type: string
  environment_name:  
    description: 'The environment name to create a deployment. If not specified, uses the value defined to "to"'
    required: false
    default: ''
    type: string
  github_token:
    description: 'GitHub token with permissions to push to the gh-pages branch'
    required: true
    type: string
  env_type:
    description: 'Environment type'
    required: true
    type: string
  gcp_credentials:
    description: "GCP credentials to upload files to GCS"
    required: false
    type: string
  bucket:
    description: "Name of the GCS Bucket"
    required: false
    type: string

runs:
  using: "composite"
  
  steps:
    - name: Mark environment as deactivated
      uses: bobheadxi/deployments@v0.4.3
      with:
        step: deactivate-env
        token: ${{ inputs.github_token }}
        env: ${{ inputs.environment_name || inputs.to }}
        desc: PR for this branch was closed
    
    - name: Create empty dir
      if: ${{ inputs.env_type == 'gh_pages' }}
      shell: bash
      run: mkdir empty_dir

    - name: Remove files from environment
      if: ${{ inputs.env_type == 'gh_pages' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./empty_dir
        destination_dir: ./${{ inputs.to }}

    - name: Authenticate with Google Cloud
      if: ${{ inputs.env_type == 'gcp' }} 
      uses: 'google-github-actions/auth@v0'      
      id: 'auth'
      with:
        credentials_json: '${{ inputs.gcp_credentials }}'

    - name: 'Set up Cloud SDK'
      if: ${{ inputs.env_type == 'gcp' }}
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Delet files from bucket
      if: ${{ inputs.env_type == 'gcp' }}
      shell: bash
      run: gsutil rm -r gs://${{ inputs.bucket }}/${{ inputs.to }}
