name: GH Pages Prune
description: 'Removes the deployment from Github Pages and disbles the environment'

# Action to prune an environment and remove the associated files deployed in Github Pages.
# Useful for example when a PR is closed and the associated deployment is not required anymore.
# Steps:
# - Disables the Github Environment object
# - Removes the directory in Github Pages
inputs:
  to:  
    description: 'Directory where the files are deployed'
    required: true
    type: string
  environment_name:  
    description: 'The environment name to create a deployment. If not specified, uses the value defined to "to"'
    required: false
    default: ''
    type: string
  github_token:
    description: 'GitHub token with permissions to push to the gh-pages branch'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Mark environment as deactivated
      uses: bobheadxi/deployments@v0.4.3
      with:
        step: deactivate-env
        token: ${{ inputs.github_token }}
        env: ${{ inputs.environment_name || inputs.to }}
        desc: PR for this branch was closed
    
    - name: Create empty dir
      shell: bash
      run: mkdir empty_dir

    - name: Remove files from environment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./empty_dir
        destination_dir: ./${{ inputs.to }}
