name: 'Reads a property from a remote JSON file'
description: 'Downloads the file and extracts the specified property'

# Action to read a remote JSON file and extract an specified property value from it.
# The property can be a path (nested property), separating the parts with "."
inputs:
  url:
    description: 'URL of the JSON file'
    required: true
  property:
    description: 'Property inside the JSON file to extract. Can be nested using "."'
    required: true

outputs:
  value:
    value: ${{ steps.get-property.outputs.value }}
    description: 'The value of the property inside the JSON'

runs:
  using: "composite"
  steps:
    - shell: bash
      id: get-property
      run: |
        curl ${{ inputs.url }} > $HOME/tmp_get_prop_action.json
        echo "value=$(jq -r '.${{ inputs.property }}' $HOME/tmp_get_prop_action.json)" >> $GITHUB_OUTPUT