name: 'GH deploy'
description: 'Deploys an static application to GitHub Pages'
inputs:
  github_token:
    description: 'GitHub token with permissions to push to the gh-pages branch'
    required: true
  to:  
    description: 'Directory where the project must be deployed to'
    required: true
  dist_dir:
    description: 'Directory where the built project is located'
    required: true
  envsubst:
    description: Substitute Environment Variables in files'
    required: false
    default: 'false'
  envsubst_file_pattern:
    description: 'File Pattern to locate files to be modified'
    required: false
  envsubst_prefix:
    description: 'Allows configuring an alternative prefix for substitution patterns if the default of ${ would cause conflicts.'
    required: false
  envsubst_suffix:
    description: 'Allows configuring an alternative suffix for substitution patterns if the default of } would cause conflicts.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./${{ inputs.dist_dir }}
    
    - name: Substitute Environment Variables in files
      if: ${{ inputs.envsubst == 'true' }}
      uses: martinmoscovich/gh-actions/envsubst@main
      with:
        path: ${{ inputs.dist_dir }}
        file_pattern: ${{ inputs.envsubst_file_pattern }}
        prefix: ${{ inputs.envsubst_prefix }}
        suffix: ${{ inputs.envsubst_suffix }}

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./${{ inputs.dist_dir }}
        destination_dir: ./${{ inputs.to }}