name: Upload an Artifact to the Cloud
description: "Upload an Artifact to a subpath of the deployment in the Cloud"

# Action to retrieve an artifact generated previously and upload it to the Cloud
#
# It will upload it to the same path as the deployment, but in a subpath
#
# Steps:
# - Download the test artifact
# - Sync to the Cloud 
# - Delete the test artifact is requested
#
inputs:
    artifact_name:  
      description: 'Artifact name to upload'
      required: true
    subpath:
      description: 'Subpath where the artifact must be uploaded'
      required: true
    delete_artifact:
      description: 'Whether the artifact must be deleted after being uploaded. Defaults to false'
      default: 'false'

    namespace:  
      description: 'The project namespace (eg adidas). Used as a prefix for the publish directory'
      required: true
    environment_name:  
      description: 'The environment name (dev or branches/some-branch) to create a deployment.'
      required: true
    cloud_service:
      description: 'Cloud Service to deploy to (supports GH Pages and GCP)'
      required: true
    cloud_credentials:
      description: 'Credentials of the cloud service where the project will be deployed to'
      required: false
    cloud_bucket:
      description: 'Name of the Cloud service (eg. GCS) bucket'
      required: false
    cloud_lb:
      description: 'Load Balancer Name'
      required: false
    cache:
      description: 'Enable or disable cache'
      required: true
    delete:
      description: 'Delete extra files in the destination not found in the source'
      required: false
      default: 'true'

runs:
  using: "composite"

  steps:
    # Copies the current action's repository to the specified location, 
    # so other actions from the same repo may be called (see sync below)
    # This allows us to use the same version of the action for both "deploy" (the current action) and sync
    - name: Copy custom action repository
      shell: bash
      run: bash ${{ github.action_path }}/../scripts/copy_actions_repo.sh
      env:
        CUSTOM_ACTION_REPO_SUBDIRECTORY: ${{ github.action_path }}
        DESTINATION_PATH: ${{ github.workspace }}/.github/actions

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: tmp-upload-artifact-cloud
        name: ${{ inputs.artifact_name }}

    - name: Upload Artifact to Cloud
      uses: ./.github/actions/ConfigureID/gh-actions/sync
      with:
        source_dir: tmp-upload-artifact-cloud
        namespace: ${{ inputs.namespace }}
        environment_name: ${{ inputs.environment_name }}/${{ inputs.subpath }}
        
        cache: ${{ inputs.cache }}
        delete: ${{ inputs.delete }}

        cloud_service: ${{ inputs.cloud_service }}
        cloud_bucket: ${{ inputs.cloud_bucket }}
        cloud_credentials: ${{ inputs.cloud_credentials }}
        cloud_lb: '${{ inputs.cloud_lb }}'
    
    - name: Delete Blob report after merge
      if: inputs.delete_artifact == 'true'
      uses: geekyeggo/delete-artifact@v5
      with:
          name: ${{ inputs.artifact_name }}
          failOnError: false