name: 'Release'
description: 'Create a release with the artifact'
inputs:
  release_filename:  
    description: 'Name of the release file'
    required: true
  dist_dir:
    description: 'Directory where the built project is located'
    required: true
  description:
    description: 'An optional body for the release'
    required: false
  tag:
    description: 'An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).'
    required: false
  source_ref:
    description: 'An optional commit reference. This will be used to create the tag if it does not exist.'
    required: false
  github_token:
    description: 'GitHub token with permissions to push to the gh-pages branch'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./${{ inputs.dist_dir }}

    - name: Compress files
      uses: papeloto/action-zip@v1
      with:
        files: ${{ inputs.dist_dir }}/
        dest: ${{ inputs.release_filename }}.zip

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ inputs.release_filename }}.zip"
        token: ${{ inputs.github_token }}
        commit: ${{ inputs.source_ref }}
        tag: ${{ inputs.tag }}
        body: ${{ inputs.description }}
        
