name: 'Release'
description: 'Create a release with the artifact'

# Create Release action
# Steps:
# - Downloads artifact from previous step
# - Compresses files
# - Creates a release in the Github repo using the tag name and the artifact
inputs:
  release_filename:  
    description: 'Name of the release file'
    required: true
  description:
    description: 'An optional body for the release'
    required: false
  tag:
    description: 'An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).'
    required: false
  source_ref:
    description: 'An optional commit reference. This will be used to create the tag if it does not exist.'
    required: false
  artifact_name:
    description: 'The name of the artifact created in a previous step. If not specified, build-output is used'
    required: false
    default: build-output
    type: string
  github_token:
    description: 'GitHub token with permissions to push to the gh-pages branch'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ./tmp

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Compress files
      run: zip -qq -r ../${{ inputs.release_filename }}.zip .
      working-directory: ./tmp

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ inputs.release_filename }}.zip"
        token: ${{ inputs.github_token }}
        commit: ${{ inputs.source_ref }}
        tag: ${{ inputs.tag }}
        body: ${{ inputs.description }}
        