name: 'Environment Variable Substitution'
#author: "Martin Moscovich @martinmoscovich"
description: 'Substitutes the values of environment variables in files'
#branding:
#  icon: "edit"
#  color: "blue"
inputs:
  path:  
    description: 'Directory where the files are located'
    required: false
    default: './'
  file_pattern:
    description: 'File Pattern to locate files to be modified'
    required: false
    default: '*'
  prefix:
    description: 'Allows configuring an alternative prefix for substitution patterns if the default of ${ would cause conflicts.'
    required: false
    default: '${'
  suffix:
    description: 'Allows configuring an alternative suffix for substitution patterns if the default of } would cause conflicts.'
    required: false
    default: '}'
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    REPLACE_PATH: ${{ inputs.path }}
    REPLACE_FILE_PATTERN: ${{ inputs.file_pattern }}
    REPLACE_PREFIX: ${{ inputs.prefix }}
    REPLACE_SUFFIX: ${{ inputs.suffix }}