name: Invalidate
description: Invalidate Cloud CDN for a specific path

# Action to Invalidate Cloud CDN for a specific path
inputs:
  cloud_credentials:
    description: 'Credentials of the cloud service where the files will be pruned'
    required: true
    type: string
  cloud_path:
    description: 'Name of the Cloud service (eg. GCS) bucket'
    required: true
    type: string
  cloud_lb:
    description: Load Balancer Name
    required: true
    type: sring
  
runs:
  using: "composite"

  steps:

    ##################
    # GCP
    ##################

    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v0'
      id: 'auth'
      with:
        credentials_json: '${{ inputs.cloud_credentials }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Invalidate Cloud CDN
      shell: bash
      run: gcloud compute url-maps invalidate-cdn-cache ${{ inputs.cloud_lb }} --path /${{ inputs.cloud_path }}/* --async
